# Generated by Django 4.1 on 2022-08-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('donde', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('unidades', models.CharField(max_length=50)),
                ('semanal', models.BooleanField()),
                ('mensual', models.BooleanField()),
                ('verificar', models.BooleanField()),
            ],
        ),
    ]
