# Generated by Django 4.1 on 2022-08-03 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_pendiente_id_alter_producto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='nombre',
        ),
        migrations.AddField(
            model_name='lista',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compras.producto'),
            preserve_default=False,
        ),
    ]
