# Generated by Django 4.1 on 2022-08-03 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_remove_lista_nombre_lista_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='donde',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='unidades',
        ),
    ]
