# Generated by Django 4.1 on 2022-08-04 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_remove_lista_donde_remove_lista_unidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='compras.producto'),
        ),
    ]
