# Generated by Django 4.1 on 2022-08-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_alter_lista_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
