# Generated by Django 4.1 on 2022-08-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_alter_lista_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendiente',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
