# Generated by Django 4.1 on 2022-08-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_alter_pendiente_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='URL',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='producto',
            name='average_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='display',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='medida',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='upc',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='producto',
            name='weighable',
            field=models.BooleanField(default=False),
        ),
    ]
