# Generated by Django 4.1 on 2022-09-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='unidades',
            field=models.CharField(default='', max_length=50),
        ),
    ]
