# Generated by Django 4.1 on 2023-08-26 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_lista_unidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encargo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('unidades', models.CharField(default='', max_length=50)),
                ('productoF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoF', to='compras.producto')),
            ],
        ),
    ]
