# Generated by Django 4.1 on 2023-08-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_encargo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encargo',
            old_name='productoF',
            new_name='producto',
        ),
    ]
