# Generated by Django 4.1 on 2024-10-30 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_rename_productof_encargo_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comidas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comida', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('unidades', models.CharField(default='', max_length=50)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoC', to='compras.producto')),
            ],
        ),
    ]
