# Generated by Django 4.1 on 2024-10-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0015_comidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
