# Generated by Django 4.1 on 2024-10-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0016_alter_comidas_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pendiente', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
