# Generated by Django 4.1 on 2024-10-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0017_pendientes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pendientes',
        ),
        migrations.RemoveField(
            model_name='pendiente',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='pendiente',
            name='pendiente',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='pendiente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
