# Generated by Django 5.2.11 on 2026-02-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0018_delete_pendientes_remove_pendiente_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaResumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('meses', models.IntegerField()),
                ('establecimiento', models.TextField(blank=True, null=True)),
                ('operacion', models.TextField(blank=True, null=True)),
                ('autorizacion', models.TextField(blank=True, null=True)),
                ('cuenta', models.TextField(blank=True, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('categoria', models.TextField(blank=True, null=True)),
                ('fecha_operacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('establecimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('operacion', models.CharField(blank=True, max_length=50, null=True)),
                ('autorizacion', models.CharField(blank=True, max_length=20, null=True)),
                ('cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'operaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperacionesHistorico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('establecimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('operacion', models.CharField(blank=True, max_length=10050, null=True)),
                ('autorizacion', models.CharField(blank=True, max_length=20, null=True)),
                ('cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_operacion', models.DateTimeField(blank=True, null=True)),
                ('periodo', models.CharField(blank=True, max_length=7, null=True)),
                ('fecha_archivado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'operaciones_historico',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='encargo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lista',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
