# Generated by Django 6.0.8 on 2026-10-01 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0019_categoriaresumen_meses_operaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialComida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comida', models.CharField(db_index=True, max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('donde', models.CharField(default='', max_length=30)),
                ('cantidad', models.IntegerField()),
                ('unidades', models.CharField(default='', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='compras.producto')),
            ],
        ),
    ]
