# Generated by Django 6.0.8 on 2026-10-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0020_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comidas',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Entre semana'), (2, 'Fin de semana')], default=1),
        ),
    ]
