# Generated by Django 6.0.8 on 2026-10-01 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0024_poblar_comidas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comidas',
        ),
    ]
